/**
 * OperisChain — Quote PDF Generator
 *
 * Client-side PDF generation using jsPDF + AutoTable.
 *
 * Architecture:
 * - Pure function (no React dependency) — can be used from hooks, API routes, or tests
 * - Bilingual (ES/EN) via Locale parameter
 * - Branded with OperisChain gradient header
 * - Scalable: add new sections by implementing PdfSection interface
 *
 * Usage:
 *   import { generateQuotePdf } from '@/lib/pdf/quote-pdf';
 *   const blob = generateQuotePdf(quoteData, 'es');
 *   // or save:
 *   generateQuotePdf(quoteData, 'es', { action: 'save' });
 */

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { QuoteDisplay } from "@/components/quote-table";
import type { Locale } from "@/lib/i18n";

// ═══════════════════════════════════════
// Types
// ═══════════════════════════════════════

export interface PdfOptions {
  /** 'blob' returns a Blob, 'save' triggers download, 'datauri' returns base64 */
  action?: "blob" | "save" | "datauri";
  /** Custom filename (without .pdf extension) */
  filename?: string;
  /** Optional client/company name to display on the quote */
  clientName?: string;
  /** Optional client company */
  clientCompany?: string;
}

interface PdfLabels {
  title: string;
  subtitle: string;
  quoteId: string;
  date: string;
  route: string;
  weight: string;
  urgency: string;
  urgencyHigh: string;
  urgencyNormal: string;
  urgencyUnknown: string;
  carrierComparison: string;
  carrier: string;
  routeCol: string;
  price: string;
  unitPrice: string;
  transit: string;
  validUntil: string;
  confidence: string;
  score: string;
  recommended: string;
  recommendationTitle: string;
  aiAnalysis: string;
  surchargeWarning: string;
  surchargeNote: string;
  footer: string;
  footerDisclaimer: string;
  page: string;
  of: string;
  preparedFor: string;
  na: string;
  days: string;
  confidenceHigh: string;
  confidenceMedium: string;
  confidenceLow: string;
  mode: string;
}

// ═══════════════════════════════════════
// Labels (i18n)
// ═══════════════════════════════════════

const labels: Record<Locale, PdfLabels> = {
  es: {
    title: "Cotizacion Comparativa",
    subtitle: "Generada por OperisChain AI",
    quoteId: "Cotizacion #",
    date: "Fecha",
    route: "Ruta",
    weight: "Peso",
    urgency: "Urgencia",
    urgencyHigh: "Urgente",
    urgencyNormal: "Normal",
    urgencyUnknown: "No especificada",
    carrierComparison: "Comparacion de Carriers",
    carrier: "Carrier",
    routeCol: "Ruta",
    price: "Precio (USD)",
    unitPrice: "Precio Unit.",
    transit: "Transito",
    validUntil: "Valido Hasta",
    confidence: "Confianza",
    score: "Puntaje",
    recommended: "* Recomendado",
    recommendationTitle: "Recomendacion IA",
    aiAnalysis: "Analisis de IA",
    surchargeWarning: "! Nota de Surcharges",
    surchargeNote:
      "Algunos precios pueden no incluir surcharges adicionales. Verificar costo total con el carrier antes de confirmar.",
    footer: "Powered by OperisChain · operischain.com",
    footerDisclaimer:
      "Esta cotizacion es informativa y no constituye una oferta comercial vinculante. Precios sujetos a confirmacion del carrier.",
    page: "Pagina",
    of: "de",
    preparedFor: "Preparado para",
    na: "N/A",
    days: "dias",
    confidenceHigh: "Alta",
    confidenceMedium: "Media",
    confidenceLow: "Baja",
    mode: "Modo",
  },
  en: {
    title: "Comparative Quotation",
    subtitle: "Generated by OperisChain AI",
    quoteId: "Quote #",
    date: "Date",
    route: "Route",
    weight: "Weight",
    urgency: "Urgency",
    urgencyHigh: "Urgent",
    urgencyNormal: "Normal",
    urgencyUnknown: "Not specified",
    carrierComparison: "Carrier Comparison",
    carrier: "Carrier",
    routeCol: "Route",
    price: "Price (USD)",
    unitPrice: "Unit Price",
    transit: "Transit",
    validUntil: "Valid Until",
    confidence: "Confidence",
    score: "Score",
    recommended: "* Recommended",
    recommendationTitle: "AI Recommendation",
    aiAnalysis: "AI Analysis",
    surchargeWarning: "! Surcharge Notice",
    surchargeNote:
      "Some prices may not include additional surcharges. Verify total cost with the carrier before confirming.",
    footer: "Powered by OperisChain · operischain.com",
    footerDisclaimer:
      "This quotation is for informational purposes and does not constitute a binding commercial offer. Prices subject to carrier confirmation.",
    page: "Page",
    of: "of",
    preparedFor: "Prepared for",
    na: "N/A",
    days: "days",
    confidenceHigh: "High",
    confidenceMedium: "Medium",
    confidenceLow: "Low",
    mode: "Mode",
  },
};

// ═══════════════════════════════════════
// Brand Colors
// ═══════════════════════════════════════

const COLORS = {
  primary: [0, 212, 255] as [number, number, number], // #00d4ff cyan
  secondary: [123, 47, 247] as [number, number, number], // #7b2ff7 purple
  dark: [10, 10, 18] as [number, number, number], // #0a0a12
  darkCard: [17, 17, 25] as [number, number, number], // #111119
  text: [226, 232, 240] as [number, number, number], // #e2e8f0
  textMuted: [148, 163, 184] as [number, number, number], // #94a3b8
  white: [255, 255, 255] as [number, number, number],
  black: [0, 0, 0] as [number, number, number],
  green: [34, 197, 94] as [number, number, number],
  yellow: [234, 179, 8] as [number, number, number],
  red: [239, 68, 68] as [number, number, number],
  tableBg: [15, 23, 42] as [number, number, number], // #0f172a
  tableAlt: [30, 41, 59] as [number, number, number], // #1e293b
  tableHead: [51, 65, 85] as [number, number, number], // #334155
  recommendedBg: [0, 212, 255, 0.08] as [number, number, number, number],
};

// ═══════════════════════════════════════
// Helpers
// ═══════════════════════════════════════

function formatCurrency(value: number): string {
  return `$${value.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

function getConfidenceLabel(score: number, l: PdfLabels): string {
  if (score >= 0.8) return l.confidenceHigh;
  if (score >= 0.5) return l.confidenceMedium;
  return l.confidenceLow;
}

function getConfidenceColor(score: number): [number, number, number] {
  if (score >= 0.8) return COLORS.green;
  if (score >= 0.5) return COLORS.yellow;
  return COLORS.red;
}

function getUrgencyLabel(
  urgency: "high" | "normal" | "unknown",
  l: PdfLabels,
): string {
  switch (urgency) {
    case "high":
      return l.urgencyHigh;
    case "normal":
      return l.urgencyNormal;
    default:
      return l.urgencyUnknown;
  }
}

function shortId(id: string): string {
  return id.substring(0, 8).toUpperCase();
}

function getUnitLabel(unitType?: string): string {
  switch (unitType) {
    case "per_ton":
      return "/ton";
    case "per_cbm":
      return "/CBM";
    case "per_kg":
      return "/kg";
    default:
      return "";
  }
}

/**
 * Sanitize text for jsPDF's built-in Helvetica font (Windows-1252 only).
 * Replaces Unicode symbols with ASCII-safe equivalents to prevent
 * garbled output (e.g. arrows showing as "l'", stars as "&").
 */
function sanitizeText(text: string): string {
  return text
    .replace(/\u2192|\u2794|\u279C|\u27A1/g, " -> ")   // → arrows
    .replace(/\u2190/g, "<- ")                           // ←
    .replace(/\u2605|\u2B50/g, "* ")                     // ★ ⭐
    .replace(/\u26A0\uFE0F?/g, "! ")                     // ⚠️
    .replace(/\u2014/g, " - ")                            // — em dash
    .replace(/\u2013/g, "-")                              // – en dash
    .replace(/\u2018|\u2019/g, "'")                       // '' smart quotes
    .replace(/\u201C|\u201D/g, '"')                       // "" smart quotes
    .replace(/\u2022/g, "- ")                             // • bullet
    .replace(/\u00B7/g, ".")                              // · middle dot
    .replace(/\u2026/g, "...")                            // … ellipsis
    .replace(/\u00A0/g, " ")                              // non-breaking space
    .replace(/\u2713|\u2714/g, "[OK] ")                   // ✓ ✔
    .replace(/\u2717|\u2718/g, "[X] ")                    // ✗ ✘
    .replace(/\u00BD/g, "1/2")                            // ½
    .replace(/\u00BC/g, "1/4")                            // ¼
    .replace(/\u00BE/g, "3/4");                           // ¾
}

// ═══════════════════════════════════════
// Main Generator
// ═══════════════════════════════════════

export function generateQuotePdf(
  quote: QuoteDisplay,
  locale: Locale,
  options: PdfOptions = {},
): Blob | string | void {
  const { action = "save", filename, clientName, clientCompany } = options;

  const l = labels[locale];
  const doc = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - margin * 2;
  let cursorY = 0;

  // ─── Header with gradient-like background ───
  drawHeader(doc, quote, l, locale, pageWidth, clientName, clientCompany);
  cursorY = 48;

  // ─── Quote Metadata ───
  cursorY = drawMetadata(doc, quote, l, margin, cursorY, contentWidth);

  // ─── Surcharge Notice (if applicable) ───
  const hasSurchargeIssues = quote.lines.some((line) =>
    line.surchargeFlags.some(
      (s) => s.status === "excluded" || s.status === "unknown",
    ),
  );
  if (hasSurchargeIssues) {
    cursorY = drawSurchargeNotice(doc, l, margin, cursorY, contentWidth);
  }

  // ─── Carrier Comparison Table ───
  cursorY = drawCarrierTable(doc, quote, l, margin, cursorY);

  // ─── AI Recommendation ───
  drawRecommendation(doc, quote, l, margin, cursorY, contentWidth);

  // ─── Footer on all pages ───
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    drawFooter(doc, l, pageWidth, pageHeight, i, totalPages);
  }

  // ─── Output ───
  const defaultFilename =
    filename ||
    `OperisChain_Quote_${quote.cargo.origin.replace(/[^a-zA-Z]/g, "")}_${quote.cargo.destination.replace(/[^a-zA-Z]/g, "")}_${shortId(quote.quoteId)}`;

  switch (action) {
    case "save":
      doc.save(`${defaultFilename}.pdf`);
      return;
    case "blob":
      return doc.output("blob");
    case "datauri":
      return doc.output("datauristring");
  }
}

// ═══════════════════════════════════════
// Section Renderers
// ═══════════════════════════════════════

function drawHeader(
  doc: jsPDF,
  quote: QuoteDisplay,
  l: PdfLabels,
  locale: Locale,
  pageWidth: number,
  clientName?: string,
  clientCompany?: string,
): void {
  // Dark background header bar
  doc.setFillColor(...COLORS.dark);
  doc.rect(0, 0, pageWidth, 44, "F");

  // Gradient accent line
  const gradientSteps = 80;
  const lineWidth = pageWidth / gradientSteps;
  for (let i = 0; i < gradientSteps; i++) {
    const ratio = i / gradientSteps;
    const r = Math.round(
      COLORS.primary[0] + (COLORS.secondary[0] - COLORS.primary[0]) * ratio,
    );
    const g = Math.round(
      COLORS.primary[1] + (COLORS.secondary[1] - COLORS.primary[1]) * ratio,
    );
    const b = Math.round(
      COLORS.primary[2] + (COLORS.secondary[2] - COLORS.primary[2]) * ratio,
    );
    doc.setFillColor(r, g, b);
    doc.rect(i * lineWidth, 44, lineWidth + 0.5, 2.5, "F");
  }

  // Logo text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(...COLORS.white);
  doc.text("OperisChain", 15, 16);

  // Title
  doc.setFontSize(11);
  doc.setTextColor(...COLORS.primary);
  doc.text(l.title, 15, 24);

  // Subtitle
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.textMuted);
  doc.text(l.subtitle, 15, 30);

  // Right side — Quote ID + Date
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.textMuted);
  const rightX = pageWidth - 15;
  doc.text(`${l.quoteId}${shortId(quote.quoteId)}`, rightX, 14, {
    align: "right",
  });
  doc.text(
    sanitizeText(`${l.date}: ${new Date(quote.generatedAt).toLocaleDateString(locale === "es" ? "es-CO" : "en-US", { year: "numeric", month: "long", day: "numeric" })}`),
    rightX,
    20,
    { align: "right" },
  );

  // Client info (if provided)
  if (clientName || clientCompany) {
    doc.setTextColor(...COLORS.white);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.text(l.preparedFor, rightX, 30, { align: "right" });
    doc.setFont("helvetica", "normal");
    if (clientCompany) {
      doc.text(clientCompany, rightX, 35, { align: "right" });
    }
    if (clientName) {
      doc.text(clientName, rightX, clientCompany ? 40 : 35, {
        align: "right",
      });
    }
  }
}

function drawMetadata(
  doc: jsPDF,
  quote: QuoteDisplay,
  l: PdfLabels,
  margin: number,
  startY: number,
  contentWidth: number,
): number {
  const y = startY + 6;
  const colWidth = contentWidth / 4;

  // Background card
  doc.setFillColor(...COLORS.darkCard);
  doc.roundedRect(margin, y - 3, contentWidth, 18, 2, 2, "F");

  const metaItems = [
    {
      label: l.route,
      value: sanitizeText(`${quote.cargo.origin} -> ${quote.cargo.destination}`),
    },
    { label: l.weight, value: `${quote.cargo.weightKg.toLocaleString()} kg` },
    { label: l.urgency, value: getUrgencyLabel(quote.cargo.urgency, l) },
    {
      label: l.carrierComparison,
      value: `${quote.lines.length} carriers`,
    },
  ];

  metaItems.forEach((item, i) => {
    const x = margin + 6 + i * colWidth;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...COLORS.textMuted);
    doc.text(item.label, x, y + 4);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(...COLORS.white);
    doc.text(item.value, x, y + 10);
  });

  return y + 20;
}

function drawSurchargeNotice(
  doc: jsPDF,
  l: PdfLabels,
  margin: number,
  startY: number,
  contentWidth: number,
): number {
  const y = startY + 2;

  // Yellow-ish warning box
  doc.setFillColor(234, 179, 8);
  doc.roundedRect(margin, y, contentWidth, 10, 1.5, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...COLORS.black);
  doc.text(l.surchargeWarning, margin + 4, y + 4);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.text(l.surchargeNote, margin + 4, y + 8);

  return y + 14;
}

function drawCarrierTable(
  doc: jsPDF,
  quote: QuoteDisplay,
  l: PdfLabels,
  margin: number,
  startY: number,
): number {
  // Sort lines by score descending (same as UI default)
  const sortedLines = [...quote.lines].sort((a, b) => b.score - a.score);

  const tableHead = [
    [
      "",
      l.carrier,
      l.routeCol,
      l.price,
      l.unitPrice,
      l.transit,
      l.validUntil,
      l.confidence,
      l.score,
    ],
  ];

  const tableBody = sortedLines.map((line) => {
    const isRecommended = line.carrier === quote.recommended;
    const totalPrice =
      line.totalPriceUSD != null ? line.totalPriceUSD : line.priceUSD;
    const unitType = line.unitType || "per_kg";
    const isUnitRate =
      unitType === "per_kg" || unitType === "per_ton" || unitType === "per_cbm";

    return [
      isRecommended ? "*" : "",
      sanitizeText(line.carrier),
      sanitizeText(line.route),
      formatCurrency(totalPrice),
      isUnitRate && totalPrice !== line.priceUSD
        ? `${formatCurrency(line.priceUSD)}${getUnitLabel(unitType)}`
        : "-",
      line.transitDays != null ? `${line.transitDays} ${l.days}` : l.na,
      line.validUntil || l.na,
      getConfidenceLabel(line.confidenceScore, l),
      `${(line.score * 100).toFixed(0)}`,
    ];
  });

  autoTable(doc, {
    startY: startY + 2,
    head: tableHead,
    body: tableBody,
    margin: { left: margin, right: margin },
    theme: "plain",
    styles: {
      font: "helvetica",
      fontSize: 8,
      cellPadding: { top: 3, bottom: 3, left: 3, right: 3 },
      textColor: COLORS.text,
      lineColor: [30, 30, 46],
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: COLORS.tableHead,
      textColor: COLORS.white,
      fontStyle: "bold",
      fontSize: 7.5,
      halign: "left",
    },
    columnStyles: {
      0: {
        cellWidth: 8,
        halign: "center",
        fontSize: 10,
        textColor: COLORS.primary,
      },
      1: { fontStyle: "bold", cellWidth: 35 },
      2: { cellWidth: 30 },
      3: { halign: "right", fontStyle: "bold", cellWidth: 28 },
      4: {
        halign: "right",
        fontSize: 7,
        textColor: COLORS.textMuted,
        cellWidth: 25,
      },
      5: { halign: "center", cellWidth: 22 },
      6: { halign: "center", cellWidth: 25 },
      7: { halign: "center", cellWidth: 22 },
      8: { halign: "center", fontStyle: "bold", cellWidth: 18 },
    },
    alternateRowStyles: {
      fillColor: COLORS.tableAlt,
    },
    didParseCell: (data) => {
      // Fill color for recommended row
      if (data.section === "body") {
        const lineIndex = data.row.index;
        const line = sortedLines[lineIndex];
        if (line && line.carrier === quote.recommended) {
          data.cell.styles.fillColor = [0, 40, 50]; // Dark cyan tint
        }

        // Confidence column color
        if (data.column.index === 7 && line) {
          data.cell.styles.textColor = getConfidenceColor(line.confidenceScore);
        }

        // Score column color
        if (data.column.index === 8) {
          data.cell.styles.textColor = COLORS.primary;
        }
      }
    },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return (doc as any).lastAutoTable.finalY + 4;
}

function drawRecommendation(
  doc: jsPDF,
  quote: QuoteDisplay,
  l: PdfLabels,
  margin: number,
  startY: number,
  contentWidth: number,
): number {
  let y = startY + 2;

  // Check if we need a new page
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + 40 > pageHeight - 20) {
    doc.addPage();
    y = 20;
  }

  // Recommendation card background
  doc.setFillColor(...COLORS.darkCard);
  const recommendedLine = quote.lines.find(
    (line) => line.carrier === quote.recommended,
  );

  // Calculate text height for the reasoning
  doc.setFontSize(8);
  const reasoningLines = doc.splitTextToSize(
    sanitizeText(quote.reasoning),
    contentWidth - 16,
  );
  const cardHeight = Math.max(30, 22 + reasoningLines.length * 3.5);

  doc.roundedRect(margin, y, contentWidth, cardHeight, 2, 2, "F");

  // Cyan left accent bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(margin, y, 2.5, cardHeight, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.primary);
  doc.text(l.recommendationTitle, margin + 8, y + 7);

  // Recommended carrier + score
  if (recommendedLine) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(...COLORS.white);
    doc.text(
      sanitizeText(`${quote.recommended} - ${formatCurrency(recommendedLine.totalPriceUSD ?? recommendedLine.priceUSD)}`),
      margin + 8,
      y + 14,
    );

    // Score badge
    const scoreText = `${(recommendedLine.score * 100).toFixed(0)}/100`;
    const scoreX = margin + contentWidth - 30;
    doc.setFillColor(...COLORS.primary);
    doc.roundedRect(scoreX, y + 4, 22, 8, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.dark);
    doc.text(scoreText, scoreX + 11, y + 9.5, { align: "center" });
  }

  // Reasoning text
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...COLORS.textMuted);
  doc.text(reasoningLines, margin + 8, y + 20);

  return y + cardHeight + 4;
}

function drawFooter(
  doc: jsPDF,
  l: PdfLabels,
  pageWidth: number,
  pageHeight: number,
  currentPage: number,
  totalPages: number,
): void {
  const footerY = pageHeight - 12;

  // Separator line
  doc.setDrawColor(...COLORS.textMuted);
  doc.setLineWidth(0.2);
  doc.line(15, footerY - 2, pageWidth - 15, footerY - 2);

  // Disclaimer
  doc.setFont("helvetica", "italic");
  doc.setFontSize(6);
  doc.setTextColor(...COLORS.textMuted);
  doc.text(l.footerDisclaimer, 15, footerY + 1);

  // Powered by
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.5);
  doc.setTextColor(...COLORS.primary);
  doc.text(l.footer, pageWidth / 2, footerY + 5, { align: "center" });

  // Page number
  doc.setTextColor(...COLORS.textMuted);
  doc.text(
    `${l.page} ${currentPage} ${l.of} ${totalPages}`,
    pageWidth - 15,
    footerY + 5,
    { align: "right" },
  );
}
